### ISSUE TITLE
Figure out expectation level and criterias

### ISSUE THREAD

**Issue by jhthorsen** [mojoconf/oslo-2014-05-24#1]
- Max of participants: 120
- Need three or more core developers who can come
- More than 40 people attends
- More than 10 people who can attend the course
- If we go from five to three organizers, we won't do the conference
- Need to have a clear communication channel
- Ask for help if you are stuck. Do _not_ delay this.

**Comment by rpcme** [comment]
what were the final results?

was there a post-mortem to see how reasonable / understated / overstated these metrics were?

**Comment by jhthorsen** [comment]
@sjn: Can you answer @rpcme's questions?

@rpcme I have some answers:
- We had sri, marcus, jberger and tempire at the conference
- I only see 31 participants in the spreadsheet. (I thought we where more...)
- We had 16 people at the training (I think)
- Me, @marcusramberg, @sjn, @ssm and @nicomen organized the conference
- We had some communication issue, but worked them out.
- We had some issue where we had to extend deadlines, but manager to pull off all the important tasks.
